Feature/dls 143 umsetzung daten cdws
AkrosAG/cmi-lesesaal pull request #102
Opened 2023-08-04 14:15 UTC by ensocon

2023-08-09 11:04 UTC, joerglang requested changes

2023-08-09 11:04 UTC, joerglang commented on CMI/Access/Harvest/CMIAIS/CMIAISArchiveRecordBuilder.cs
> +                Log.Information($"CDWS Root is {Settings.Default.CdwsRoot}");
Bitte als Verbose oder Debug. Ansonsten zuviel Lärm im normalen Log

2023-08-09 11:04 UTC, joerglang commented on CMI/Access/Common/ElasticRecordMapping.json
> +          "version": { "type": "integer" }
Nützt uns die Version etwas? Können sie sicher speichern, kein Problem. 
Frage mich nur, warum wir die Version speichern, aber z.B. FileType nicht, die wir ja vom CDWS erhalten.

2023-08-09 11:04 UTC, joerglang commented on CMI/Contract/Common/ElasticArchiveRecord.cs
> +    }
FileType allenfalls? Ist natürlich durch extension abgedeckt, aber eventuell hilfreich?

2023-08-09 11:04 UTC, joerglang commented on CMI/Web.Clients/web-core/src/lib/core/model/entity/files.ts
> +version: string;
fehlt noch Art und Extension

2023-08-09 11:04 UTC, joerglang commented on CMI/Web.Clients/web-frontend/src/app/modules/client/components/detail/files/fileSection.component.html
> +				<span>{{file.filename}}</span>
Titel als Hyperlink und mit Grösse hintendran. 
Grösse nicht einfach nur in Bytes sondern mit einer Pipe in KB oder MB umrechnen

2023-08-09 11:04 UTC, joerglang commented on CMI/Web/CMI.Web.Frontend/App_Data_Template/Sustainsys.Saml2.Tests.pfx
Entfernen aus dem Commit

2023-08-09 11:04 UTC, joerglang commented on CMI/Web/CMI.Web.Frontend/api/Elastic/ElasticService.cs
> +            searchRequest.Source = new SourceFilter {Excludes = Infer.Fields("all", "primaryData.items.content","files.base64Content")};
Noch Leerzeichen nach Komma

2023-08-09 11:04 UTC, joerglang commented on CMI/Web/CMI.Web.Frontend/api/Controllers/FileController.cs
> +                var record = GetRecord(id, access);
Braucht doch hier eine andere Methode die spezifisch nur den Base64 Content zurückliefert.
Da der Base64Content ja defaultmässig ausgeklammert ist.

2023-08-09 14:10 UTC, ensocon commented on CMI/Contract/Common/ElasticArchiveRecord.cs
> +    }
Für den Typ verwenden wir Extension

2023-08-09 14:13 UTC, ensocon commented on CMI/Access/Harvest/CMIAIS/CMIAISArchiveRecordBuilder.cs
> +                Log.Information($"CDWS Root is {Settings.Default.CdwsRoot}");
Debug Level gesetzt

2023-08-09 14:15 UTC, ensocon commented on CMI/Access/Common/ElasticRecordMapping.json
> +          "version": { "type": "integer" }
FileType wird über die Extension abgedeckt , Version habe ich mit aufgenommen um diese eventuell im Frontend anzeigen zu können.

2023-08-09 14:17 UTC, ensocon commented on CMI/Web.Clients/web-core/src/lib/core/model/entity/files.ts
> +version: string;
Art und Extension wurde hinzugefügt.

2023-08-09 14:20 UTC, ensocon commented on CMI/Web/CMI.Web.Frontend/api/Elastic/ElasticService.cs
> +            searchRequest.Source = new SourceFilter {Excludes = Infer.Fields("all", "primaryData.items.content","files.base64Content")};
Leerzeichen hinzugefügt.

2023-08-09 14:29 UTC, ensocon commented on CMI/Web/CMI.Web.Frontend/App_Data_Template/Sustainsys.Saml2.Tests.pfx
Commit wieder zurückgenommen.

2023-08-14 06:33 UTC, joerglang approved these changes
Vor dem Mergen bitte noch in der Web.config auf den produktiven Shibboleth umstellen

2023-08-14 06:33 UTC, joerglang commented on CMI/Web.Clients/web-frontend/src/app/modules/client/components/detail/files/fileSection.component.html
> +			<br/><span>Art:&#20;{{file.art}}</span>
Könntest du diese Zeil noch in ein *ngIf verpacken, so dass nicht ein unnötiger <br/> und Label gerendert wird, wenn keine Art und/oder Beschreibung da ist?

2023-08-14 06:33 UTC, joerglang commented on CMI/Web/CMI.Web.Frontend/Web.config
> +      <add name="AuthenticationModule" type="CMI.Web.Common.Auth.Sibboleth.LocalEthDevClaimsAuthenticationHttpModule, CMI.Web.Common" />
Vor finalem Checkin wieder ändern

2023-08-14 16:55 UTC, merged