Ladebildschirm
AkrosAG/cmi-lesesaal pull request #126
Opened 2023-09-15 09:57 UTC by PeterEttwein-Evelix

2023-09-15 12:46 UTC, joerglang requested changes

2023-09-15 12:46 UTC, joerglang commented on CMI/Web.Clients/web-core/src/lib/core/components/ui/loader/loader.component.less
> +			background: #B7352D;
Nein, gehört nicht hierher.
Less wird kompilllert. 
Für die Startseite ist ein eigenes externes CSS hinzuzufügen, wo das CSS für den Loader hinkommt. Dann können wir die Farben wechseln, ohne neu zu kompilieren.

2023-09-15 12:46 UTC, joerglang commented on CMI/Web.Clients/web-frontend/src/app/modules/client/components/header/content/headerContent.component.html
> +		<img src="./assets/img/logo.svg" onerror="this.onerror = null; this.src = './assets/img/logo.png'"
Der alt Text müsste ja auch übersetzt werden...

2023-09-15 12:46 UTC, joerglang commented on CMI/Web.Clients/web-frontend/src/assets/img/logo.png
Dieses Logo, respektive Logos müssten ja auch noch in den Custom-Files abgelegt werden. Diese werden dann ja ersetzt.

2023-09-15 12:46 UTC, joerglang commented on CMI/Web.Clients/web-frontend/src/config/loading-texts.js
Auch dieses in die Custom-Files

2023-09-15 12:46 UTC, joerglang commented on CMI/Web.Clients/web-frontend/src/index.html
> +			.cmi-hint {
Alle dieses "Inline-Styles while booting" in eine externe Datei verschieben. die dann ebenfalls in den Asset\css Folder kommt, sowie in den Custom-Folder.

2023-09-18 07:10 UTC, PeterEttwein-Evelix commented on CMI/Web.Clients/web-frontend/src/app/modules/client/components/header/content/headerContent.component.html
> +		<img src="./assets/img/logo.svg" onerror="this.onerror = null; this.src = './assets/img/logo.png'"
Das mache ich mit dem Task: [DLS-236](https://cmiag.myjetbrains.com/youtrack/issue/DLS-236) [Draft] [HSA] Grundlegende Designelemente und Startseite P-C

2023-09-18 13:23 UTC, joerglang requested changes
Der Index.html im M-C ist nicht in Ordnung

2023-09-18 13:23 UTC, joerglang commented on CMI/Web.Clients/web-management/src/index.html
> +	<link rel="stylesheet" href="client/styles.3f3b3d4c9a1ecc170446.css" media="print" onload="this.media='all'">
Was sind das für Styles??

2023-09-18 13:23 UTC, joerglang commented on CMI/Web.Clients/web-management/src/index.html
> +	<noscript><link rel="stylesheet" href="client/styles.3f3b3d4c9a1ecc170446.css"></noscript>
Dito?

2023-09-18 13:23 UTC, joerglang commented on CMI/Web.Clients/web-management/src/index.html
> +	<script src="client/runtime-es2018.55780b5b63453b9ba6b6.js" type="module"></script>
Und diese hier?

2023-09-18 14:48 UTC, joerglang approved these changes

2023-09-18 14:58 UTC, merged