Feature/DLS-272-Statusinfomation-Benutzer
AkrosAG/cmi-lesesaal pull request #156
Opened 2023-11-03 15:03 UTC by ensocon

### Todo's

- [ ] Alle Texte welche im UI ersichtlich sind übersetzbar.
- [ ] Unit- / BDD-Tests sind erstellt _(Frage lautet immer: Warum braucht es keine Unit-/BDD-Tests)_.
- [ ] Keine Todo’s im Code _(nur mit Begründung)_.
- [ ] ReSharper Kriterien sind alle grün _(mind. bei neuen Klassen, wenn möglich auch bei geänderten)_.
- [ ] Changelog Eintrag geschrieben _(bei Major oder Minor bump)_.

__Reminder__
- [ ] Dokumentation ist aktualisiert _(Updatealeitung, Wiki, Readme.md, Installation.md)_.
- [ ] YouTrack-Ticket ist mit der Umsetzungsbeschreibung aktualisiert. 
- [ ] Status des YouTrack-Tickets ist auf «Behoben» gesetzt.
- [ ] Branch in alle benötigten Release-Branches zurückführen gemäss «zu lösen in».

__Dokumentationen__
- [CMI-Webclients Dos and Don’ts](https://cminformatik.atlassian.net/l/cp/usT6kKy5)

2023-11-03 15:48 UTC, joerglang requested changes

2023-11-03 15:48 UTC, joerglang commented on CMI/Web.Clients/web-frontend/src/app/modules/client/components/user/status-info-user/status-info-user.component.less
> +.passportAndIdCountriesSelect {
Brauchen wir dies?
Generell: Brauchen wir diese CSS Ergänzungen?

2023-11-03 16:27 UTC, ensocon commented on CMI/Web.Clients/web-frontend/src/app/modules/client/components/user/status-info-user/status-info-user.component.less
> +.passportAndIdCountriesSelect {
Nein , css Inhalt habe ich entfernt

2023-11-05 12:57 UTC, joerglang approved these changes

2023-11-05 12:57 UTC, merged