Feature/dls 310 anpassungen der seiten kontoeröffnung und benutzerstatus
AkrosAG/cmi-lesesaal pull request #168
Opened 2023-11-28 17:43 UTC by PeterEttwein-Evelix

2023-11-28 19:40 UTC, joerglang requested changes
Generell habe ich so das Bauchgefühl, dass 26 angpasste Dateien einfach etwas viel sind. Aber dies kannst du gerne Oliver so weitergeben, damit die ETH sieht, dass dies nicht einfach nur Textänderungen sind.
Generell gibt es aber schon noch Dinge zu verbessern.
Vor allem im Static-Controller sollte es eigentlich keine Änderungen geben. Zumindest muss auf jeden Fall der Text der zurückgegeben werden soll, in einem Content-Wrapper drin sein.

Ferner habe ich gesehen, dass bei den CustomerScripts bei den verschiedenen Archiven eine unterschiedliche Anzahl von Dateien und Benennungen gibt. Diese bitte bereinigen, wenn noch Leichen rumliegen sollten.

2023-11-28 19:40 UTC, joerglang commented on CMI/Web.Clients/web-frontend/src/app/components/account/accountPage.component.ts
> +			this.activeColumn = '3';
Stimmt dies? Wenn jemand registriert ist, dann ist die mittlere Spalte aktiv. Wenn jemand identifiziert ist, dann ist es die letzte Spalte.

2023-11-28 19:40 UTC, joerglang commented on CMI/Web.Clients/web-frontend/src/app/components/account/accountTypeInfoList/accountTypeInfoList.component.html
> +						<a cli class="text-toggle collapsed" data-toggle="collapse" href="#tableBody" aria-expanded="false" aria-controls="tableBody" >
cli hat wohl nichts zu suchen da. Dann das Leerzeichen vor > sollte auch weg.

2023-11-28 19:40 UTC, joerglang commented on CMI/Web.Clients/web-frontend/src/app/components/account/accountTypeInfoList/accountTypeInfoList.component.html
> +							<span class="text-expanded" >
Leerzeichen vor > weg

2023-11-28 19:40 UTC, joerglang commented on CMI/Web.Clients/web-frontend/src/app/components/register/registerPageInfo/registerPageInfo.component.html
> +		<button class="btn"  (click)="cancel()">
Auch zuviel Whitespace

2023-11-28 19:40 UTC, joerglang commented on CMI/Web.Clients/web-frontend/src/config/css/custom.css
> +.user-col-icon{
Das muss dann auch noch alles in die anderen Custom.css rein. Nicht vergessen.

2023-11-28 19:40 UTC, joerglang commented on CMI/Web/CMI.Web.Frontend/api/Controllers/StaticController.cs
> +                if (contentNode == null)
Nein, ist gefährlich. Hätten wir es so nicht gehabt, dann hätte der eine Bug-Bounty alle Dateien vom Server auslesen können.  Die HTML Seite muss einen Marker haben. D.h. es muss immer einen Content-Node geben und der soll auch immer durch den ProcessStaticMarkupForSpa durchlaufen, oder zumindest was ähnliches

2023-11-29 09:37 UTC, PeterEttwein-Evelix commented
> Generell habe ich so das Bauchgefühl, dass 26 angpasste Dateien einfach etwas viel sind. Aber dies kannst du gerne Oliver so weitergeben, damit die ETH sieht, dass dies nicht einfach nur Textänderungen sind. Generell gibt es aber schon noch Dinge zu verbessern. Vor allem im Static-Controller sollte es eigentlich keine Änderungen geben. Zumindest muss auf jeden Fall der Text der zurückgegeben werden soll, in einem Content-Wrapper drin sein.
> 
> Ferner habe ich gesehen, dass bei den CustomerScripts bei den verschiedenen Archiven eine unterschiedliche Anzahl von Dateien und Benennungen gibt. Diese bitte bereinigen, wenn noch Leichen rumliegen sollten.

Jetzt sind 37 Dateien, aber 12 neue html-Dateien im CustumScript Ordner und 4  html-Dateien im SourceCode

2023-11-29 17:53 UTC, joerglang approved these changes

2023-11-29 17:53 UTC, merged