DLS-132 Servicestatus ausblenden
AkrosAG/cmi-lesesaal pull request #23
Opened 2022-09-15 08:05 UTC by uguenther

2022-09-15 09:10 UTC, joerglang requested changes
Hallo Uli
Es erschliesst sich mir in keiner Weise, wie/warum im Contract Bereich plötzlich Settings definiert werden sollen. Wennschon würde diese zum Manager gehören, aber da man diesen ganzen Service eh rausschmeissen könnte, genügt es die Setting nur im M-C hinzuzufügen.
Bitte alles aus "Contract" rausnehmen.

Beim M-C ist die Setting hinzuzufügen, aber es muss ja nicht zwigend ein eigenes File sein. Warum nicht einfach zu dem bestehenden cmi.settings.config hinzufügen?

2022-09-15 09:10 UTC, joerglang commented on CMI/Contract/Monitoring/CMI.Contract.Monitoring.csproj
> +    <Compile Include="Properties\MonitoringSettings.Designer.cs">
???

2022-09-15 09:10 UTC, joerglang commented on CMI/Contract/Monitoring/Properties/MonitoringSettings.settings
> +﻿<?xml version='1.0' encoding='utf-8'?>
???

2022-09-15 09:10 UTC, joerglang commented on CMI/Contract/Monitoring/app.config
> +<configSections>
???

2022-09-15 09:10 UTC, joerglang commented on CMI/Web/CMI.Web.Management/App_Data_Template/app.monitoring.config
> +﻿<CMI.Contract.Monitoring.Properties.MonitoringSettings>
Warum ein extra config file, und warum nicht in den cmi.settings.config?

2022-09-15 09:10 UTC, joerglang commented on CMI/Web/CMI.Web.Management/api/Controllers/MonitoringController.cs
> +            var ignored = MonitoringSettings.Default.ExcludedService.Split(',');
Settings bitte injecten...

2022-09-15 10:51 UTC, uguenther commented on CMI/Web/CMI.Web.Management/App_Data_Template/app.monitoring.config
> +﻿<CMI.Contract.Monitoring.Properties.MonitoringSettings>
Du hattest recht. Ich lese den Wert aus den cmi.settings.config. Ist einfacher und simple. Keine extra files und DI notwendig

2022-09-15 12:54 UTC, joerglang requested changes

2022-09-15 12:54 UTC, joerglang commented on CMI/Web/CMI.Web.Management/api/Controllers/MonitoringController.cs
> +            var excludedService  = WebHelper.GetStringSetting("monitoringExcludedService", "").Split(',');
Sorry, aber bitte nicht so. --> Dependency Injection wenn immer möglich.
Zudem haben wir ja für andere Settings direkte Properties gemacht um darauf zugreifen zu können, oder nicht? Bitte identisch handhaben.

2022-09-16 07:55 UTC, joerglang approved these changes

2022-09-16 07:55 UTC, merged