Feature/dls 423 rosetta umbau
AkrosAG/cmi-lesesaal pull request #240
Opened 2024-05-22 11:41 UTC by PeterEttwein-Evelix

2024-05-22 14:37 UTC, joerglang requested changes
Da hast du glaube ich zuviel in die Engine verschoben. 
Ziel ist es, dass der DIR-Provider und der Rosetta-Provider am Ende "symmetrisch" sind, d.h. beide haben das genau gleiche Interface und die Grundabläufe im AppendPackageConsumer und DownloadPackageConsumer müssen identisch sein, d.h. man müsste den Originalen Code dort stehen lassen können. Bzw. nur so anpassen, dass beide Provider funktionieren würden.

Ich glaube da müssen wir nochmals schauen. Ich nehme die Aufwände dann gerne auf Evelix (Ausbildung).

2024-05-22 14:37 UTC, joerglang commented on CMI/Engine/PackageMetadata/Systems/Rosetta/RepositoryPackageBuilder.cs
> +namespace CMI.Engine.PackageMetadata.Systems.Rosetta
Dieses File würde immer noch zum Manager gehören.

2024-05-22 14:37 UTC, joerglang commented on CMI/Engine/PackageMetadata/Systems/Rosetta/RepositoryPackageBuilder.cs
> +        public Task CreateMetadataXml(RepositoryPackage repositoryPackage)
Nur diese Methode gehört in die Engine...

2024-05-22 14:37 UTC, joerglang commented on CMI/Engine/PackageMetadata/Systems/Rosetta/IRepositoryPackageBuilder.cs
> +    public interface IRepositoryPackageBuilder
Warum ein neues Interface?
Es gibt ein bestehendes IPackageHandler mit der einzigen Methode "CreateMetadataXml".
Man hätte dieses verwenden müssen, damit man wirklich mit Providern arbeiten kann.

Das Erzeugen des Packages und das Zippen des Files ist nicht Aufgabe der Engine. Es geht in der Engine alleine darum Logik-Code/Berechnungen etc. auszulagern. Die anderen Methoden hätten bleiben können wo sie waren.

2024-05-22 14:37 UTC, joerglang commented on CMI/Engine/PackageMetadata/app.config
> +<startup><supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.8" /></startup><applicationSettings>
Diese Settings gehören nicht in die Engine

2024-05-22 14:37 UTC, joerglang commented on CMI/Manager/Repository/Consumer/AppendPackageConsumer.cs
> +                context.Message.ArchiveRecord?.PrimaryData.Clear();
Macht dies der Provider vom DIR?
Müssen wir es hier so machen?
Wird dieses Property dann nicht einfach ersetzt innerhalb der Methode?

2024-05-22 14:37 UTC, joerglang commented on CMI/Manager/Repository/Consumer/DownloadPackageConsumer.cs
> +                // We are not waiting for it to end, because we want to free the consumer as early as possible
Warum warten wir nicht? Und wo?
In diesem Code sehe ich nirgends etwas, dass darauf hindeutet.

2024-05-24 07:34 UTC, PeterEttwein-Evelix commented on CMI/Manager/Repository/Consumer/AppendPackageConsumer.cs
> +                context.Message.ArchiveRecord?.PrimaryData.Clear();
Ja, das kommt von der DIR implementierung

2024-05-24 07:41 UTC, PeterEttwein-Evelix commented on CMI/Manager/Repository/Consumer/DownloadPackageConsumer.cs
> +                // We are not waiting for it to end, because we want to free the consumer as early as possible
ist der orginal Code vom DIR

2024-05-24 09:07 UTC, joerglang approved these changes

2024-05-24 09:13 UTC, merged