First set of changes for review
AkrosAG/cmi-lesesaal pull request #272
Opened 2024-12-17 10:18 UTC by ramarathna

2024-12-18 09:42 UTC, joerglang requested changes
Hi Ramu
Very good. I made some smaller changes im some md-files.

Also I added some comments where you need to change a few little things.

What is missing is the "update" of the readme.md file. That one is important. It also links to a installation.md file which doesn't really have content. Either delete that file and remove the link, or check if in the GitHub of the Federal Archives this file does contain valid text.

2024-12-18 09:42 UTC, joerglang commented on CMI/Web/CMI.Web.Common/Auth/Sibboleth/LocalDevClaimsAuthenticationHttpModule.cs
> +                        new ShibbolethAttributeValue("mail", ""),
Can you change the givenName and surname for all those user to some fantasy names like characters from Harry Potter or James Bond or something. 
And the E-Mail to something like 1234@google.com or similar. But with a comment saying that you have to put a real email into the field, if you'd like to receive confirmations and such things.

2024-12-18 09:42 UTC, joerglang commented on Test/Utilities/Template.Tests/HelperTests.cs
> +            data["InteractiveUser"] = new Person {Name = "Peter", EMail = ""};
Put a fantasy email like james@bond.com or whatever you think is funny

2024-12-18 09:42 UTC, joerglang commented on Test/Web/Common.Tests/Helpers/AuthControllerHelperTests.cs
> +                EmailAddress = ""
Same here

2024-12-18 09:42 UTC, joerglang commented on CMI/Manager/DocumentConverter/SftpServer.cs
> +        private const string password = @"";
add here a password like "changeMePlease!"

2025-01-29 14:34 UTC, PeterEttwein-Evelix approved these changes

2025-01-30 08:18 UTC, joerglang requested changes
Hallo Ramu
Es gibt noch 2-3 Punkte die du anschauen müsstest.

2025-01-30 08:18 UTC, joerglang commented on CMI/Engine/Asset/PreProcess/ScanProcessor.cs
> +        public ScanProcessor(ImageHelper imageHelper, ScansZusammenfassenSettings settings, bool skipLicenseSetup = false)
Warum gibt es neu einen Fall, wo man die Lizenz überspringen will? Scheint mir sehr komisch. Welchen Grund gibt es dafür?

2025-01-30 08:18 UTC, joerglang commented on CMI/Engine/Asset/PreProcess/ScanProcessor.cs
> +                    // Retrieve the license content from application settings
Dieser selbe Code hast du nun schon 3 Mail in dieser Library wiederholt. Es wäre an der Zeit, diesen Code in eine eigene Methode oder Extension auszulagern. Meinst du nicht?

2025-01-30 08:18 UTC, joerglang commented on CMI/Engine/Asset/Properties/Settings.settings
> +    </Setting>
Nicht vergessen dieses neue Setting im Staging File für die ETH zu ergänzen, falls es nicht schon da ist. 
Und im Staging-File müsste er dann wohl anders heissen, weil der Build-Output den Platzhalter so viel ich weiss aktualisiert.

2025-05-12 14:02 UTC, merged